//! Python code emitter.
//!
//! Converts a `rustpython_ast::Mod` back into Python source text.  In
//! Phase 0 this is a hand-written pretty-printer that covers the Python
//! subset needed for round-trip testing.  Later phases will switch to a
//! vendored `ruff_python_codegen` + `ruff_python_formatter` pipeline.

mod printer;

pub use printer::Emitter;

use rustpython_ast::{text_size::TextRange, Constant, Expr, Mod, Stmt};

/// Header comment written at the top of every compiled `.py` output file.
pub const EMIT_HEADER: &str = "# generated by tyc — do not edit\n";

/// Options that control compiled emission (as opposed to plain round-trip
/// emission).  Populated from the desugarer's [`DesugarInfo`] output.
#[derive(Debug, Default)]
pub struct EmitOptions {
    /// Prepend `from dataclasses import dataclass` and inject
    /// `@dataclass(slots=True)` before bare class definitions.
    pub inject_dataclass: bool,
    /// Prepend `from pydantic import BaseModel` and add `BaseModel` as the
    /// base class of bare class definitions.
    pub inject_pydantic: bool,
}

/// Emit a [`Mod`] AST node as Python source text (plain round-trip).
pub fn emit(module: &Mod) -> String {
    let mut emitter = Emitter::new();
    emitter.emit_mod(module);
    emitter.finish()
}

/// Emit a compiled Typhon module as Python source with:
/// - A `# generated by tyc — do not edit` header
/// - Helper imports injected after any module docstring / `__future__` imports
/// - `@dataclass(slots=True)` injected before bare class definitions when
///   `options.inject_dataclass` is set
///
/// The ordering honours Python's module structure rules: a module docstring
/// must be the very first statement, and `from __future__ import ...` must
/// appear before any other non-docstring code.
pub fn emit_compiled(module: &Mod, options: &EmitOptions) -> String {
    let stmts = match module {
        Mod::Module(m) => m.body.as_slice(),
        _ => {
            let mut out = String::from(EMIT_HEADER);
            let mut emitter = Emitter::new_compiled(options);
            emitter.emit_mod(module);
            out.push_str(&emitter.finish());
            return out;
        }
    };

    // Split: preamble (docstring + future imports) must precede all other
    // imports; our injected helpers go immediately after the preamble.
    let split = preamble_len(stmts);
    let (preamble, body) = stmts.split_at(split);

    let mut out = String::new();

    // 1. Preamble — docstring and __future__ imports must come first.
    if !preamble.is_empty() {
        let mut pre = Emitter::new();
        for s in preamble {
            pre.emit_stmt(s);
        }
        out.push_str(&pre.finish());
        out.push('\n');
    }

    // 2. Generated-file header.
    out.push_str(EMIT_HEADER);

    // 3. Injected helper imports.
    let needs_imports = options.inject_dataclass || options.inject_pydantic;
    if options.inject_dataclass {
        out.push_str("from dataclasses import dataclass\n");
    }
    if options.inject_pydantic {
        out.push_str("from pydantic import BaseModel\n");
    }
    if needs_imports {
        out.push('\n');
    }

    // 4. Remaining module body (with decorator / base-class injection).
    let mut emitter = Emitter::new_compiled(options);
    for s in body {
        emitter.emit_stmt(s);
    }
    out.push_str(&emitter.finish());
    out
}

/// Returns the number of leading statements that form the module preamble:
/// an optional module docstring followed by zero or more
/// `from __future__ import ...` statements.
fn preamble_len(stmts: &[Stmt<TextRange>]) -> usize {
    let mut i = 0;

    // Module docstring: the first statement is a bare string-literal expression.
    if let Some(Stmt::Expr(e)) = stmts.first() {
        if matches!(e.value.as_ref(), Expr::Constant(c) if matches!(&c.value, Constant::Str(_))) {
            i += 1;
        }
    }

    // Future imports must immediately follow (or start, if no docstring).
    while let Some(Stmt::ImportFrom(imp)) = stmts.get(i) {
        if imp
            .module
            .as_ref()
            .map(|m| m.as_str() == "__future__")
            .unwrap_or(false)
        {
            i += 1;
        } else {
            break;
        }
    }

    i
}
