//! Python code emitter.
//!
//! Converts a `rustpython_ast::Mod` back into Python source text.  In
//! Phase 0 this is a hand-written pretty-printer that covers the Python
//! subset needed for round-trip testing.  Later phases will switch to a
//! vendored `ruff_python_codegen` + `ruff_python_formatter` pipeline.

mod printer;

pub use printer::Emitter;

use rustpython_ast::Mod;

/// Header comment written at the top of every compiled `.py` output file.
pub const EMIT_HEADER: &str = "# generated by tyc — do not edit\n";

/// Options that control compiled emission (as opposed to plain round-trip
/// emission).  Populated from the desugarer's [`DesugarInfo`] output.
#[derive(Debug, Default)]
pub struct EmitOptions {
    /// Prepend `from dataclasses import dataclass` and inject
    /// `@dataclass(slots=True)` before bare class definitions.
    pub inject_dataclass: bool,
    /// Prepend `from pydantic import BaseModel`.
    pub inject_pydantic: bool,
}

/// Emit a [`Mod`] AST node as Python source text (plain round-trip).
pub fn emit(module: &Mod) -> String {
    let mut emitter = Emitter::new();
    emitter.emit_mod(module);
    emitter.finish()
}

/// Emit a compiled Typhon module as Python source with:
/// - A `# generated by tyc — do not edit` header
/// - Helper imports injected at the top (dataclasses / pydantic)
/// - `@dataclass(slots=True)` injected before bare class definitions when
///   `options.inject_dataclass` is set
pub fn emit_compiled(module: &Mod, options: &EmitOptions) -> String {
    let mut out = String::from(EMIT_HEADER);

    if options.inject_dataclass {
        out.push_str("from dataclasses import dataclass\n");
    }
    if options.inject_pydantic {
        out.push_str("from pydantic import BaseModel\n");
    }
    if options.inject_dataclass || options.inject_pydantic {
        out.push('\n');
    }

    let mut emitter = Emitter::new_compiled(options);
    emitter.emit_mod(module);
    out.push_str(&emitter.finish());
    out
}
