[package]
name = "ttc-types"
version.workspace = true
edition.workspace = true
description = "Nominal and structural type checker for Typhon"

[dependencies]
rustpython-ast = { workspace = true }
ttc-syntax = { workspace = true }
ttc-resolve = { workspace = true }
ttc-diagnostics = { workspace = true }

[dev-dependencies]
rustpython-parser = { workspace = true }
