// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// https://astro.build/config
export default defineConfig({
  site: 'https://codehalwell.github.io',
  base: '/Typhon',
  integrations: [
    starlight({
      title: 'Typhon',
      description:
        'A statically-typed, stricter superset of Python that compiles to clean CPython 3.13+ — with zero runtime dependency on the toolchain.',
      logo: {
        light: './src/assets/logo-light.svg',
        dark: './src/assets/logo-dark.svg',
        replacesTitle: false,
      },
      favicon: '/favicon.svg',
      social: {
        github: 'https://github.com/CodeHalwell/Typhon',
      },
      editLink: {
        baseUrl:
          'https://github.com/CodeHalwell/Typhon/edit/main/docs-site/src/content/docs/',
      },
      customCss: ['./src/styles/custom.css'],
      head: [
        {
          tag: 'meta',
          attrs: {
            name: 'theme-color',
            content: '#0f172a',
          },
        },
      ],
      lastUpdated: true,
      pagination: true,
      tableOfContents: { minHeadingLevel: 2, maxHeadingLevel: 4 },
      expressiveCode: {
        themes: ['github-dark-default', 'github-light'],
        styleOverrides: {
          borderRadius: '0.5rem',
        },
      },
      sidebar: [
        {
          label: 'Introduction',
          items: [
            { label: 'Welcome to Typhon', slug: 'introduction/welcome' },
            { label: 'The Ethos of Typhon', slug: 'introduction/ethos' },
            { label: 'Design Decisions', slug: 'introduction/design-decisions' },
            { label: 'Goals and Non-Goals', slug: 'introduction/goals' },
            { label: 'Comparison with Other Languages', slug: 'introduction/comparisons' },
            { label: 'Project Status', slug: 'introduction/status' },
          ],
        },
        {
          label: 'Getting Started',
          items: [
            { label: 'Installation', slug: 'getting-started/installation' },
            { label: 'Hello World', slug: 'getting-started/hello-world' },
            { label: 'Project Layout', slug: 'getting-started/project-layout' },
            { label: 'Your First Real Program', slug: 'getting-started/first-program' },
            { label: 'Editor Setup', slug: 'getting-started/editor-setup' },
          ],
        },
        {
          label: 'Language Tour',
          items: [
            { label: 'Five Rules of Typhon', slug: 'tour/five-rules' },
            { label: 'Values and Bindings', slug: 'tour/values-bindings' },
            { label: 'Functions', slug: 'tour/functions' },
            { label: 'Control Flow', slug: 'tour/control-flow' },
            { label: 'Classes and Models', slug: 'tour/classes' },
            { label: 'Error Handling', slug: 'tour/error-handling' },
            { label: 'Sealed Unions and Match', slug: 'tour/sealed-unions' },
            { label: 'Generics and Interfaces', slug: 'tour/generics-interfaces' },
            { label: 'Async and Concurrency', slug: 'tour/async' },
            { label: 'Advanced Features', slug: 'tour/advanced' },
          ],
        },
        {
          label: 'Type System',
          items: [
            { label: 'Overview', slug: 'types/overview' },
            { label: 'Primitives', slug: 'types/primitives' },
            { label: 'Collections', slug: 'types/collections' },
            { label: 'Nullable Types', slug: 'types/nullable' },
            { label: 'Flow Narrowing', slug: 'types/narrowing' },
            { label: 'Generics (PEP 695)', slug: 'types/generics' },
            { label: 'Sealed Unions', slug: 'types/sealed-unions' },
            { label: 'Interfaces (Protocols)', slug: 'types/interfaces' },
            { label: 'The Unsafe Boundary', slug: 'types/unsafe' },
            { label: 'Type Aliases', slug: 'types/aliases' },
          ],
        },
        {
          label: 'Language Reference',
          items: [
            { label: 'Lexical Structure', slug: 'reference/lexical' },
            { label: 'let and mut', slug: 'reference/let-mut' },
            { label: 'Function Definitions', slug: 'reference/functions' },
            { label: 'class, model, class!', slug: 'reference/classes' },
            { label: 'impl and extend', slug: 'reference/impl-extend' },
            { label: 'interface', slug: 'reference/interface' },
            { label: 'Result, Ok, Err', slug: 'reference/result' },
            { label: 'The ? Operator', slug: 'reference/question-operator' },
            { label: 'with-chains', slug: 'reference/with-chains' },
            { label: 'guard', slug: 'reference/guard' },
            { label: 'match', slug: 'reference/match' },
            { label: 'async, await, gather, go', slug: 'reference/async' },
            { label: 'lazy', slug: 'reference/lazy' },
            { label: 'comptime', slug: 'reference/comptime' },
            { label: 'Pipes (|>)', slug: 'reference/pipes' },
            { label: '@pure and @memo', slug: 'reference/pure-memo' },
            { label: 'unsafe', slug: 'reference/unsafe' },
            { label: 'Decorators', slug: 'reference/decorators' },
            { label: 'Imports', slug: 'reference/imports' },
            { label: 'Operators and Precedence', slug: 'reference/operators' },
            { label: 'Grammar Cheat Sheet', slug: 'reference/grammar' },
          ],
        },
        {
          label: 'How Typhon Lowers',
          items: [
            { label: 'Lowering Overview', slug: 'lowering/overview' },
            { label: 'Classes → dataclass', slug: 'lowering/classes' },
            { label: 'Result → typhon_runtime', slug: 'lowering/result' },
            { label: 'gather: → TaskGroup', slug: 'lowering/gather' },
            { label: 'go → spawn registry', slug: 'lowering/go' },
            { label: 'lazy → proxies', slug: 'lowering/lazy' },
            { label: 'comptime → inlined literals', slug: 'lowering/comptime' },
            { label: 'extend → free functions', slug: 'lowering/extend' },
            { label: 'Source Maps (.py.map)', slug: 'lowering/source-maps' },
            { label: 'The typhon_runtime module', slug: 'lowering/runtime' },
          ],
        },
        {
          label: 'Tooling (tyc CLI)',
          items: [
            { label: 'Overview', slug: 'cli/overview' },
            { label: 'tyc init', slug: 'cli/init' },
            { label: 'tyc check', slug: 'cli/check' },
            { label: 'tyc build', slug: 'cli/build' },
            { label: 'tyc fmt', slug: 'cli/fmt' },
            { label: 'tyc run', slug: 'cli/run' },
            { label: 'tyc lsp', slug: 'cli/lsp' },
            { label: 'tyc repl', slug: 'cli/repl' },
            { label: 'tyc debug', slug: 'cli/debug' },
            { label: 'tyc trace', slug: 'cli/trace' },
            { label: 'tyc profile', slug: 'cli/profile' },
            { label: 'tyc migrate', slug: 'cli/migrate' },
            { label: 'tyc ty', slug: 'cli/ty' },
            { label: 'tyc stubtest', slug: 'cli/stubtest' },
            { label: 'tyc add / remove / sync', slug: 'cli/packages' },
            { label: 'Exit Codes', slug: 'cli/exit-codes' },
          ],
        },
        {
          label: 'Configuration',
          items: [
            { label: 'typhon.toml Overview', slug: 'configuration/overview' },
            { label: '[project]', slug: 'configuration/project' },
            { label: '[python]', slug: 'configuration/python' },
            { label: '[emit]', slug: 'configuration/emit' },
            { label: '[strictness]', slug: 'configuration/strictness' },
            { label: '[env]', slug: 'configuration/env' },
            { label: '[dependencies]', slug: 'configuration/dependencies' },
            { label: 'Recommended Presets', slug: 'configuration/presets' },
          ],
        },
        {
          label: 'Interop with Python',
          items: [
            { label: 'Interop Overview', slug: 'interop/overview' },
            { label: 'Calling Python from Typhon', slug: 'interop/calling-python' },
            { label: 'Writing .dty Stubs', slug: 'interop/dty-stubs' },
            { label: '.pyi Emission', slug: 'interop/pyi' },
            { label: 'Stub Drift (tyc check --stubs)', slug: 'interop/stub-drift' },
            { label: 'Pydantic Boundary Models', slug: 'interop/pydantic' },
            { label: 'Class Escape Hatches', slug: 'interop/class-escape' },
          ],
        },
        {
          label: 'Diagnostics Catalog',
          items: [
            { label: 'Reading Diagnostics', slug: 'diagnostics/reading' },
            { label: 'Type & Inference Errors', slug: 'diagnostics/type-errors' },
            { label: 'Binding Errors', slug: 'diagnostics/binding-errors' },
            { label: 'Nullability Errors', slug: 'diagnostics/nullability' },
            { label: 'Class Errors', slug: 'diagnostics/class-errors' },
            { label: 'Result Errors', slug: 'diagnostics/result-errors' },
            { label: 'Match Errors', slug: 'diagnostics/match-errors' },
            { label: 'Async Errors', slug: 'diagnostics/async-errors' },
            { label: 'Purity Errors', slug: 'diagnostics/purity-errors' },
            { label: 'Stub Errors', slug: 'diagnostics/stub-errors' },
            { label: 'Compile & Interface Errors', slug: 'diagnostics/compile-errors' },
          ],
        },
        {
          label: 'Recipes & Patterns',
          items: [
            { label: 'Patterns Index', slug: 'recipes/patterns' },
            { label: 'Migrating from Python', slug: 'recipes/migrating' },
            { label: 'CLI Application', slug: 'recipes/cli-application' },
            { label: 'HTTP API with Pydantic', slug: 'recipes/http-api' },
            { label: 'Concurrent Data Fetching', slug: 'recipes/concurrent-fetch' },
            { label: 'Build-Time Env Validation', slug: 'recipes/env-validation' },
            { label: 'Errors as Values', slug: 'recipes/errors-as-values' },
            { label: 'State Machines with Sealed Unions', slug: 'recipes/state-machines' },
            { label: 'Wrapping an Untyped Library', slug: 'recipes/wrapping-library' },
            { label: 'Testing Typhon Code', slug: 'recipes/testing' },
            { label: 'CI Integration', slug: 'recipes/ci' },
          ],
        },
        {
          label: 'Common Pitfalls',
          items: [
            { label: 'Top Pitfalls', slug: 'pitfalls/top' },
            { label: 'Python Habits to Drop', slug: 'pitfalls/python-habits' },
            { label: 'Performance Gotchas', slug: 'pitfalls/performance' },
          ],
        },
        {
          label: 'Compiler Internals',
          items: [
            { label: 'Architecture Overview', slug: 'internals/architecture' },
            { label: 'The Pipeline', slug: 'internals/pipeline' },
            { label: 'Workspace Layout', slug: 'internals/workspace' },
            { label: 'Salsa Queries', slug: 'internals/salsa' },
            { label: 'The Vendored Ruff Fork', slug: 'internals/ruff-fork' },
            { label: 'Adding a Diagnostic', slug: 'internals/adding-diagnostic' },
            { label: 'Contributing', slug: 'internals/contributing' },
          ],
        },
        {
          label: 'Project',
          items: [
            { label: 'Roadmap', slug: 'project/roadmap' },
            { label: 'Risks and Mitigations', slug: 'project/risks' },
            { label: 'Prior Art', slug: 'project/prior-art' },
            { label: 'Naming', slug: 'project/naming' },
            { label: 'Performance Baseline', slug: 'project/performance' },
            { label: 'Glossary', slug: 'project/glossary' },
            { label: 'Frequently Asked Questions', slug: 'project/faq' },
          ],
        },
      ],
    }),
  ],
});
