[package]
name = "tyc"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Typhon compiler and language server — single binary"

[[bin]]
name = "tyc"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
miette = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
toml_edit = { workspace = true }
ruff_python_ast    = { workspace = true }
ruff_python_parser = { workspace = true }
ruff_text_size     = { workspace = true }

tyc-syntax      = { workspace = true }
tyc-diagnostics = { workspace = true }
tyc-emit        = { workspace = true }
tyc-format      = { workspace = true }
tyc-db          = { workspace = true }
tyc-resolve     = { workspace = true }
tyc-types       = { workspace = true }
tyc-analyse     = { workspace = true }
tyc-desugar     = { workspace = true }
tyc-lsp         = { workspace = true }
tyc-vm          = { workspace = true }
tyc-venv          = { path = "../tyc-venv" }
tempfile        = { workspace = true }
notify          = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }
itoa = "1.0.18"

[dev-dependencies]
tempfile   = { workspace = true }
serde_json = { workspace = true }
