[package]
name = "tyc-resolve"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Name resolution and scope construction for Typhon"

[dependencies]
rustpython-ast = { workspace = true }
tyc-syntax = { workspace = true }
tyc-diagnostics = { workspace = true }

[dev-dependencies]
rustpython-parser = { workspace = true }
