//! `tyc build` — full compilation pipeline.
//!
//! Reads `typhon.toml`, discovers `.ty` source files under the configured
//! `src` directory, runs the full preprocess → parse → resolve → type-check
//! → emit pipeline on each, and writes the resulting `.py` files to the
//! configured `out` directory (mirroring the source tree structure).
//!
//! Output files are only written once all source files have been checked
//! with no errors, so a failing build never leaves stale or partial artifacts.

use std::path::PathBuf;

use clap::Args;
use miette::{miette, Result};

use tyc_db::{build_file, TycDatabase};
use tyc_diagnostics::{Diagnostics, TycError};

use crate::commands::util::collect_ty_files;
use crate::config::TyphonConfig;

/// Header prepended to every emitted `.py` file.
const GENERATED_HEADER: &str = "# generated by tyc — do not edit\n\n";

/// Arguments for `tyc build`.
#[derive(Args, Debug)]
pub struct BuildArgs {
    /// Project directory (defaults to current directory).
    #[arg(value_name = "PATH", default_value = ".")]
    pub path: PathBuf,

    /// Write output to this directory instead of the configured `out` dir.
    #[arg(long, short = 'o', value_name = "DIR")]
    pub out: Option<PathBuf>,

    /// Skip ruff post-formatting of emitted Python (reserved; formatting is Phase 2).
    #[arg(long)]
    pub no_format: bool,
}

pub fn run(args: BuildArgs) -> Result<()> {
    let project_dir = args
        .path
        .canonicalize()
        .unwrap_or_else(|_| args.path.clone());

    // `typhon.toml` is required for `tyc build`.
    let (config_path, config) = match TyphonConfig::load(&project_dir)
        .map_err(|e| miette!("{}", e))?
    {
        Some(pair) => pair,
        None => {
            return Err(miette!(
                "no typhon.toml found in {} or any parent directory\n\
                 run `tyc init` to create a new project",
                project_dir.display()
            ))
        }
    };

    let config_dir = config_path
        .parent()
        .map(|p| p.to_path_buf())
        .unwrap_or_else(|| project_dir.clone());

    let src_dir = config_dir.join(&config.project.src);
    let out_dir = args
        .out
        .clone()
        .unwrap_or_else(|| config_dir.join(&config.project.out));

    if !src_dir.exists() {
        return Err(miette!(
            "source directory '{}' does not exist\n\
             check the `[project] src` setting in typhon.toml",
            src_dir.display()
        ));
    }

    let paths = collect_ty_files(&src_dir)?;

    if paths.is_empty() {
        eprintln!("tyc build: no .ty files found in {}", src_dir.display());
        return Ok(());
    }

    // Phase 1: run the full pipeline over every source file, collecting
    // diagnostics and buffering outputs. Nothing is written to disk yet.
    let mut all_diags = Diagnostics::new();
    let mut pending: Vec<(PathBuf, String)> = Vec::new();
    let mut db = TycDatabase::new();

    for path in &paths {
        let source = match std::fs::read_to_string(path) {
            Ok(s) => s,
            Err(e) => {
                all_diags.push_error(TycError::io(path.display().to_string(), &e));
                continue;
            }
        };

        let (file_diags, emitted) =
            build_file(&mut db, path.display().to_string(), source);
        all_diags.extend(file_diags);

        if let Some(python_src) = emitted {
            let rel = path.strip_prefix(&src_dir).unwrap_or(path.as_path());
            let out_path = out_dir.join(rel).with_extension("py");
            let mut content =
                String::with_capacity(GENERATED_HEADER.len() + python_src.len());
            content.push_str(GENERATED_HEADER);
            content.push_str(&python_src);
            pending.push((out_path, content));
        }
    }

    // Phase 2: report errors and stop without touching the output tree.
    if all_diags.has_errors() {
        for err in all_diags.errors() {
            eprintln!("{:?}", miette::Report::new_boxed(Box::new(err.clone())));
        }
        return Err(miette!(
            "{} error(s) in {} file(s)",
            all_diags.error_count(),
            paths.len()
        ));
    }

    // Phase 3: all clean — create the output directory and write files.
    std::fs::create_dir_all(&out_dir)
        .map_err(|e| miette!("cannot create output directory {}: {}", out_dir.display(), e))?;

    let mut emit_count = 0usize;
    for (out_path, content) in &pending {
        if let Some(parent) = out_path.parent() {
            if let Err(e) = std::fs::create_dir_all(parent) {
                eprintln!(
                    "{:?}",
                    miette!("cannot create {}: {}", parent.display(), e)
                );
                continue;
            }
        }
        match std::fs::write(out_path, content.as_bytes()) {
            Ok(()) => emit_count += 1,
            Err(e) => eprintln!(
                "{:?}",
                miette!("cannot write {}: {}", out_path.display(), e)
            ),
        }
    }

    println!("built {} file(s) → {}", emit_count, out_dir.display());
    Ok(())
}
