//! `tyc build` — full compilation pipeline.
//!
//! Reads `typhon.toml`, discovers `.ty` source files under the configured
//! `src` directory, runs the full preprocess → parse → resolve → type-check
//! → emit pipeline on each, and writes the resulting `.py` files to the
//! configured `out` directory (mirroring the source tree structure).

use std::path::PathBuf;

use clap::Args;
use miette::{miette, Result};

use tyc_db::{build_file, TycDatabase};
use tyc_diagnostics::{Diagnostics, TycError};

use crate::config::TyphonConfig;

/// Header prepended to every emitted `.py` file.
const GENERATED_HEADER: &str = "# generated by tyc — do not edit\n\n";

/// Arguments for `tyc build`.
#[derive(Args, Debug)]
pub struct BuildArgs {
    /// Project directory (defaults to current directory).
    #[arg(value_name = "PATH", default_value = ".")]
    pub path: PathBuf,

    /// Write output to this directory instead of the configured `out` dir.
    #[arg(long, short = 'o', value_name = "DIR")]
    pub out: Option<PathBuf>,

    /// Skip formatting the emitted Python.
    #[arg(long)]
    pub no_format: bool,
}

pub fn run(args: BuildArgs) -> Result<()> {
    let project_dir = args
        .path
        .canonicalize()
        .unwrap_or_else(|_| args.path.clone());

    // `typhon.toml` is required for `tyc build`.
    let (config_path, config) = match TyphonConfig::load(&project_dir)
        .map_err(|e| miette!("{}", e))?
    {
        Some(pair) => pair,
        None => {
            return Err(miette!(
                "no typhon.toml found in {} or any parent directory\n\
                 run `tyc init` to create a new project",
                project_dir.display()
            ))
        }
    };

    let config_dir = config_path
        .parent()
        .map(|p| p.to_path_buf())
        .unwrap_or_else(|| project_dir.clone());

    let src_dir = config_dir.join(&config.project.src);
    let out_dir = args
        .out
        .clone()
        .unwrap_or_else(|| config_dir.join(&config.project.out));

    if !src_dir.exists() {
        return Err(miette!(
            "source directory '{}' does not exist\n\
             check the `[project] src` setting in typhon.toml",
            src_dir.display()
        ));
    }

    std::fs::create_dir_all(&out_dir)
        .map_err(|e| miette!("cannot create output directory {}: {}", out_dir.display(), e))?;

    let mut all_diags = Diagnostics::new();
    let mut file_count = 0usize;
    let mut emit_count = 0usize;
    let mut db = TycDatabase::new();

    collect_ty_files(&src_dir, &mut |path| {
        file_count += 1;

        let source = match std::fs::read_to_string(path) {
            Ok(s) => s,
            Err(e) => {
                all_diags.push_error(TycError::io(path.display().to_string(), &e));
                return;
            }
        };

        let (file_diags, emitted) =
            build_file(&mut db, path.display().to_string(), source);
        all_diags.extend(file_diags);

        if let Some(python_src) = emitted {
            // src/foo/bar.ty  →  out/foo/bar.py
            let rel = path.strip_prefix(&src_dir).unwrap_or(path.as_path());
            let out_path = out_dir.join(rel).with_extension("py");

            if let Some(parent) = out_path.parent() {
                if let Err(e) = std::fs::create_dir_all(parent) {
                    all_diags.push_error(TycError::io(parent.display().to_string(), &e));
                    return;
                }
            }

            let mut content = String::with_capacity(GENERATED_HEADER.len() + python_src.len());
            content.push_str(GENERATED_HEADER);
            content.push_str(&python_src);

            match std::fs::write(&out_path, content.as_bytes()) {
                Ok(()) => emit_count += 1,
                Err(e) => all_diags
                    .push_error(TycError::io(out_path.display().to_string(), &e)),
            }
        }
    })?;

    if all_diags.has_errors() {
        for err in all_diags.errors() {
            eprintln!("{:?}", miette::Report::new_boxed(Box::new(err.clone())));
        }
        return Err(miette!(
            "{} error(s) in {} file(s)",
            all_diags.error_count(),
            file_count
        ));
    }

    if file_count == 0 {
        eprintln!("tyc build: no .ty files found in {}", src_dir.display());
    } else {
        println!(
            "built {} file(s) → {}",
            emit_count,
            out_dir.display()
        );
    }

    Ok(())
}

fn collect_ty_files<F>(root: &PathBuf, f: &mut F) -> Result<()>
where
    F: FnMut(&PathBuf),
{
    if root.is_file() {
        if root.extension().map(|e| e == "ty").unwrap_or(false) {
            f(root);
        }
        return Ok(());
    }
    if root.is_dir() {
        let entries = std::fs::read_dir(root)
            .map_err(|e| miette!("cannot read directory {}: {}", root.display(), e))?;
        let mut paths: Vec<PathBuf> = entries
            .map(|res| res.map(|e| e.path()))
            .collect::<std::io::Result<Vec<_>>>()
            .map_err(|e| miette!("cannot read directory entry in {}: {}", root.display(), e))?;
        paths.sort();
        for path in paths {
            collect_ty_files(&path, f)?;
        }
    }
    Ok(())
}
