//! `tyc init` — scaffold a new Typhon project.

use std::path::PathBuf;

use clap::Args;
use miette::{miette, Result};

use crate::config::{
    EmitConfig, EnvConfig, ProjectConfig, PythonConfig, StrictnessConfig, TyphonConfig,
};

/// Arguments for `tyc init`.
#[derive(Args, Debug)]
pub struct InitArgs {
    /// Name of the new project (defaults to the directory name).
    #[arg(value_name = "NAME")]
    pub name: Option<String>,

    /// Directory to initialise (defaults to current directory).
    #[arg(long, short = 'd', value_name = "DIR", default_value = ".")]
    pub dir: PathBuf,
}

pub fn run(args: InitArgs) -> Result<()> {
    let dir = args.dir.canonicalize().unwrap_or(args.dir.clone());

    let name = args.name.unwrap_or_else(|| {
        dir.file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("myproject")
            .to_owned()
    });

    // Refuse to overwrite an existing typhon.toml.
    let config_path = dir.join("typhon.toml");
    if config_path.exists() {
        return Err(miette!("typhon.toml already exists in {}", dir.display()));
    }

    // Create directory structure.
    let src_dir = dir.join("src");
    let tests_dir = dir.join("tests");
    std::fs::create_dir_all(&src_dir).map_err(|e| miette!("cannot create src/: {}", e))?;
    std::fs::create_dir_all(&tests_dir).map_err(|e| miette!("cannot create tests/: {}", e))?;

    // Write typhon.toml.
    let config = TyphonConfig {
        project: ProjectConfig {
            name: name.clone(),
            version: "0.1.0".into(),
            src: "src".into(),
            out: "build".into(),
        },
        python: PythonConfig::default(),
        emit: EmitConfig::default(),
        strictness: StrictnessConfig::default(),
        env: EnvConfig::default(),
        dependencies: Default::default(),
        dev_dependencies: Default::default(),
    };
    let toml_str = config
        .to_toml_string()
        .map_err(|e| miette!("cannot serialise typhon.toml: {}", e))?;
    std::fs::write(&config_path, toml_str)
        .map_err(|e| miette!("cannot write typhon.toml: {}", e))?;

    // Write a starter main.ty — refuse to overwrite if it already exists.
    let main_ty_path = src_dir.join("main.ty");
    if main_ty_path.exists() {
        return Err(miette!(
            "src/main.ty already exists in {}; remove it first to re-scaffold",
            dir.display()
        ));
    }
    let main_ty = format!(
        r#"# {name} — entry point
#
# generated by `tyc init`

let greeting: str = "Hello from Typhon!"

def main() -> None:
    print(greeting)


main()
"#,
        name = name
    );
    std::fs::write(&main_ty_path, main_ty)
        .map_err(|e| miette!("cannot write src/main.ty: {}", e))?;

    println!("Initialised Typhon project `{}` in {}", name, dir.display());
    println!("  typhon.toml");
    println!("  src/main.ty");
    println!("  tests/");

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn init_creates_project_structure() {
        let tmp = tempfile::tempdir().unwrap();
        let args = InitArgs {
            name: Some("myapp".into()),
            dir: tmp.path().to_path_buf(),
        };
        run(args).unwrap();
        assert!(
            tmp.path().join("typhon.toml").exists(),
            "typhon.toml missing"
        );
        assert!(tmp.path().join("src").is_dir(), "src/ dir missing");
        assert!(
            tmp.path().join("src/main.ty").exists(),
            "src/main.ty missing"
        );
        assert!(tmp.path().join("tests").is_dir(), "tests/ dir missing");
    }

    #[test]
    fn init_writes_project_name_into_toml() {
        let tmp = tempfile::tempdir().unwrap();
        let args = InitArgs {
            name: Some("coolproject".into()),
            dir: tmp.path().to_path_buf(),
        };
        run(args).unwrap();
        let toml = std::fs::read_to_string(tmp.path().join("typhon.toml")).unwrap();
        assert!(
            toml.contains("coolproject"),
            "project name not in typhon.toml"
        );
    }

    #[test]
    fn init_rejects_existing_toml() {
        let tmp = tempfile::tempdir().unwrap();
        // First init succeeds.
        run(InitArgs {
            name: Some("proj".into()),
            dir: tmp.path().to_path_buf(),
        })
        .unwrap();
        // Second init on the same dir must fail.
        let result = run(InitArgs {
            name: Some("proj".into()),
            dir: tmp.path().to_path_buf(),
        });
        assert!(
            result.is_err(),
            "expected error when typhon.toml already exists"
        );
    }

    #[test]
    fn init_writes_main_ty_with_let_not_deprecated_val() {
        // Regression guard: the scaffolded `main.ty` must use `let`, the
        // current binding keyword.  `val` was an early-development spelling
        // that has since been removed from the lexer; reintroducing it in
        // the template would generate a project that doesn't type-check on
        // the first `tyc check`.
        let tmp = tempfile::tempdir().unwrap();
        let args = InitArgs {
            name: Some("regression".into()),
            dir: tmp.path().to_path_buf(),
        };
        run(args).unwrap();
        let body = std::fs::read_to_string(tmp.path().join("src/main.ty")).unwrap();
        assert!(
            !body.split_whitespace().any(|tok| tok == "val"),
            "scaffold leaked the deprecated `val` keyword:\n{body}"
        );
        assert!(
            body.contains("let "),
            "scaffold should use the current `let` keyword:\n{body}"
        );
    }

    #[test]
    fn init_uses_dir_name_when_no_name_given() {
        let tmp = tempfile::tempdir().unwrap();
        let args = InitArgs {
            name: None,
            dir: tmp.path().to_path_buf(),
        };
        // Should succeed (infers name from temp dir name).
        run(args).unwrap();
        assert!(tmp.path().join("typhon.toml").exists());
    }
}
