//! `tyc init` — scaffold a new Typhon project.

use std::path::PathBuf;

use clap::Args;
use miette::{miette, Result};

/// Arguments for `tyc init`.
#[derive(Args, Debug)]
pub struct InitArgs {
    /// Name of the new project (defaults to the directory name).
    #[arg(value_name = "NAME")]
    pub name: Option<String>,

    /// Directory to initialise (defaults to current directory).
    #[arg(long, short = 'd', value_name = "DIR", default_value = ".")]
    pub dir: PathBuf,
}

pub fn run(args: InitArgs) -> Result<()> {
    let (dir, name) = match args.name {
        Some(name) => {
            // An explicit name is the user's choice, so it is validated
            // rather than rewritten: it goes verbatim into `typhon.toml`,
            // the generated `pyproject.toml` and the scaffolded source, and
            // a quote or a newline in it produced a manifest that could not
            // be parsed by the very next command.
            let name = validate_project_name(&name)?;
            let target = args.dir.join(&name);
            std::fs::create_dir_all(&target)
                .map_err(|e| miette!("cannot create {}: {}", target.display(), e))?;
            let canonical = target.canonicalize().unwrap_or(target);
            (canonical, name)
        }
        None => {
            let base = args.dir.canonicalize().unwrap_or(args.dir.clone());
            // Inferred from the directory: a directory named `my project`
            // is perfectly ordinary, so sanitise rather than refuse.
            let inferred =
                sanitise_project_name(base.file_name().and_then(|n| n.to_str()).unwrap_or(""));
            (base, inferred)
        }
    };

    let config_path = dir.join("typhon.toml");
    let src_dir = dir.join("src");
    let tests_dir = dir.join("tests");
    let main_ty_path = src_dir.join("main.ty");

    // Every refusal comes before the first write (W4-14): `src/main.ty`
    // already present used to fail only after `typhon.toml` and `tests/` were
    // written, so the re-run then failed on the half-made scaffold. A path
    // that is a symlink — even a dangling one, which `exists()` reports as
    // absent — counts as present: the scaffold never writes through a link.
    let present = |p: &std::path::Path| std::fs::symlink_metadata(p).is_ok();
    if present(&config_path) {
        return Err(miette!("typhon.toml already exists in {}", dir.display()));
    }
    if present(&main_ty_path) {
        return Err(miette!(
            "src/main.ty already exists in {}; remove it first to re-scaffold",
            dir.display()
        ));
    }

    std::fs::create_dir_all(&src_dir).map_err(|e| miette!("cannot create src/: {}", e))?;
    std::fs::create_dir_all(&tests_dir).map_err(|e| miette!("cannot create tests/: {}", e))?;

    let toml_str = render_typhon_toml(&name);
    tyc_format::atomic_write(&config_path, toml_str.as_bytes())
        .map_err(|e| miette!("cannot write typhon.toml: {}", e))?;

    let main_ty = render_main_ty(&name);
    tyc_format::atomic_write(&main_ty_path, main_ty.as_bytes())
        .map_err(|e| miette!("cannot write src/main.ty: {}", e))?;

    println!("Initialised Typhon project `{}` in {}", name, dir.display());
    println!("  typhon.toml");
    println!("  src/main.ty");
    println!("  tests/");

    Ok(())
}

fn render_main_ty(name: &str) -> String {
    // The scaffold demonstrates: a `frozen` dataclass with a separate
    // `impl` block (Rule 4), a function-scope `mut` binding, a
    // `Result[T, E]`-returning function with `?` propagation, and a
    // `match` on `Ok`/`Err`. Everything here type-checks under the
    // strict defaults in the generated `typhon.toml`.
    format!(
        r#"# {name} — entry point
#
# generated by `tyc init`. Edit freely.

# Module scope defaults to `let`, so the keyword is optional here.
let greeting: str = "Hello from Typhon!"


# A `frozen` dataclass: immutable, hashable, slotted at runtime. The
# `frozen` modifier follows the class name.
class Greeting frozen:
    name: str


# Methods live in `impl Greeting:` blocks, not in the class body (Rule 4).
impl Greeting:
    def greet(self) -> str:
        return f"Hello, {{self.name}}, from Typhon!"


# `Result[T, E]` + `?` for railway-style error propagation. `parse_count`
# returns `Ok(int)` on success and `Err(str)` on failure; downstream callers
# forward the error with `?`.
def parse_count(s: str) -> Result[int, str]:
    try:
        return Ok(int(s))
    except ValueError:
        return Err(f"not an int: {{s}}")


def doubled_count(s: str) -> Result[int, str]:
    let n: int = parse_count(s)?
    return Ok(n * 2)


def main() -> None:
    print(greeting)

    let hello: Greeting = Greeting(name="{name}")
    print(hello.greet())

    # Local `mut` binding: rebindable, but only to new values of the
    # declared type. `let` would forbid the increment below.
    mut count: int = 0
    count = count + 1
    print(f"count is now {{count}}")

    match doubled_count("21"):
        case Ok(value):
            print(f"doubled: {{value}}")
        case Err(reason):
            print(f"failed: {{reason}}")


if __name__ == "__main__":
    main()
"#,
        name = name
    )
}

/// A project name usable everywhere the scaffold writes it: a TOML basic
/// string, a `pyproject.toml` `[project] name`, and a directory. The shape
/// is PEP 508's: letters, digits, and `.`/`-`/`_` between them.
fn project_name_is_valid(name: &str) -> bool {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    if !first.is_ascii_alphanumeric() {
        return false;
    }
    let Some(last) = name.chars().next_back() else {
        return false;
    };
    if !last.is_ascii_alphanumeric() {
        return false;
    }
    name.chars()
        .all(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '-' | '_'))
}

fn validate_project_name(name: &str) -> Result<String> {
    if project_name_is_valid(name) {
        return Ok(name.to_owned());
    }
    let suggestion = sanitise_project_name(name);
    Err(miette!(
        "`{name}` is not a usable project name. Use letters, digits, and `.`, `-` or `_` between them (PEP 508) — try `{suggestion}`."
    ))
}

/// Coerce an arbitrary directory name into a valid project name. Every
/// character outside the allowed set becomes `-`, runs collapse, and the
/// ends are trimmed; an empty result falls back to `myproject`.
fn sanitise_project_name(raw: &str) -> String {
    let mut out = String::with_capacity(raw.len());
    for c in raw.chars() {
        if c.is_ascii_alphanumeric() || matches!(c, '.' | '-' | '_') {
            out.push(c);
        } else if !out.ends_with('-') {
            out.push('-');
        }
    }
    let trimmed = out.trim_matches(|c: char| !c.is_ascii_alphanumeric());
    if trimmed.is_empty() {
        "myproject".to_owned()
    } else {
        trimmed.to_owned()
    }
}

fn render_typhon_toml(name: &str) -> String {
    format!(
        r#"[project]
name = "{name}"
version = "0.1.0"
src = "src"
out = "build"

[python]
target = "3.13"
# free-threaded = true   # opt into Python 3.13t free-threaded build

# [optimise]
# level = 1   # enable auto-memoise/auto-gather/auto-parallel/pgo-memoise (as `tyc build -O` does)

[emit]
class-default = "dataclass"     # only "dataclass" today; use the `model` keyword per class for pydantic
format = true                   # post-process emitted Python through ruff format

[strictness]
no-implicit-any = true          # require explicit element types on list/dict/tuple/set
unused-import = "warn"          # "error" promotes to a build break
exhaustive-match = "error"      # require `match` on sealed unions to cover every variant
methods-in-class-body = "warn"  # "error" promotes Rule 4 to a build break
suggest-gather = true           # advice when independent awaits could run concurrently
# auto-memoise / auto-gather / auto-parallel / pgo-memoise follow `[optimise] level`
# (off at 0, on at 1 or under `tyc build -O`); setting one here overrides both.
require-with = "warn"           # "error" / "off" — open()/socket()/connect() outside `with` is a leak
blocking-in-async = "warn"      # "error" / "off" — time.sleep / requests.get inside async def
allow-secret-comptime = false   # silence `tyc::contains_secret_literal` warnings

# Run `tyc migrate path/to/foo.py` to convert typed Python to Typhon.
"#,
        name = name
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn init_creates_project_structure() {
        let tmp = tempfile::tempdir().unwrap();
        let args = InitArgs {
            name: Some("myapp".into()),
            dir: tmp.path().to_path_buf(),
        };
        run(args).unwrap();
        let project = tmp.path().join("myapp");
        assert!(project.join("typhon.toml").exists(), "typhon.toml missing");
        assert!(project.join("src").is_dir(), "src/ dir missing");
        assert!(project.join("src/main.ty").exists(), "src/main.ty missing");
        assert!(project.join("tests").is_dir(), "tests/ dir missing");
    }

    #[test]
    fn init_with_name_creates_subdirectory() {
        let tmp = tempfile::tempdir().unwrap();
        let args = InitArgs {
            name: Some("hello".into()),
            dir: tmp.path().to_path_buf(),
        };
        run(args).unwrap();
        assert!(
            tmp.path().join("hello/typhon.toml").exists(),
            "typhon.toml should land in the named subdirectory"
        );
        assert!(
            !tmp.path().join("typhon.toml").exists(),
            "typhon.toml must not leak into the parent directory"
        );
    }

    #[test]
    fn init_writes_project_name_into_toml() {
        let tmp = tempfile::tempdir().unwrap();
        let args = InitArgs {
            name: Some("coolproject".into()),
            dir: tmp.path().to_path_buf(),
        };
        run(args).unwrap();
        let toml = std::fs::read_to_string(tmp.path().join("coolproject/typhon.toml")).unwrap();
        assert!(
            toml.contains("coolproject"),
            "project name not in typhon.toml"
        );
    }

    #[test]
    fn init_rejects_existing_toml() {
        let tmp = tempfile::tempdir().unwrap();
        run(InitArgs {
            name: Some("proj".into()),
            dir: tmp.path().to_path_buf(),
        })
        .unwrap();
        let result = run(InitArgs {
            name: Some("proj".into()),
            dir: tmp.path().to_path_buf(),
        });
        assert!(
            result.is_err(),
            "expected error when typhon.toml already exists"
        );
    }

    #[test]
    fn init_writes_main_ty_with_let_not_deprecated_val() {
        let tmp = tempfile::tempdir().unwrap();
        let args = InitArgs {
            name: Some("regression".into()),
            dir: tmp.path().to_path_buf(),
        };
        run(args).unwrap();
        let body = std::fs::read_to_string(tmp.path().join("regression/src/main.ty")).unwrap();
        assert!(
            !body.split_whitespace().any(|tok| tok == "val"),
            "scaffold leaked the deprecated `val` keyword:\n{body}"
        );
        assert!(
            body.contains("let "),
            "scaffold should use the current `let` keyword:\n{body}"
        );
    }

    #[test]
    fn init_uses_dir_name_when_no_name_given() {
        let tmp = tempfile::tempdir().unwrap();
        let args = InitArgs {
            name: None,
            dir: tmp.path().to_path_buf(),
        };
        run(args).unwrap();
        assert!(tmp.path().join("typhon.toml").exists());
    }

    #[test]
    fn scaffold_main_ty_contains_class_impl_mut_result() {
        let tmp = tempfile::tempdir().unwrap();
        run(InitArgs {
            name: Some("scaffold".into()),
            dir: tmp.path().to_path_buf(),
        })
        .unwrap();
        let body = std::fs::read_to_string(tmp.path().join("scaffold/src/main.ty")).unwrap();
        for needle in [
            "class Greeting frozen",
            "impl Greeting",
            "mut count",
            "Result[int, str]",
            "Ok(",
            "Err(",
            "?",
            "def main() -> None",
            "print(",
        ] {
            assert!(
                body.contains(needle),
                "scaffold main.ty missing `{needle}`:\n{body}"
            );
        }
    }

    #[test]
    fn scaffold_typhon_toml_documents_class_default() {
        let tmp = tempfile::tempdir().unwrap();
        run(InitArgs {
            name: Some("docs".into()),
            dir: tmp.path().to_path_buf(),
        })
        .unwrap();
        let toml = std::fs::read_to_string(tmp.path().join("docs/typhon.toml")).unwrap();
        let line = toml
            .lines()
            .find(|l| l.trim_start().starts_with("class-default"))
            .expect("class-default key missing from generated typhon.toml");
        assert!(
            line.contains('#'),
            "class-default needs an inline `# ...` explanation: {line}"
        );
        assert!(
            line.contains("dataclass") && line.contains("pydantic"),
            "class-default comment should mention both accepted values: {line}"
        );
    }

    #[test]
    fn scaffold_typhon_toml_includes_allow_secret_comptime() {
        let tmp = tempfile::tempdir().unwrap();
        run(InitArgs {
            name: Some("docs".into()),
            dir: tmp.path().to_path_buf(),
        })
        .unwrap();
        let toml = std::fs::read_to_string(tmp.path().join("docs/typhon.toml")).unwrap();
        assert!(
            toml.contains("allow-secret-comptime = false"),
            "allow-secret-comptime missing from generated typhon.toml:\n{toml}"
        );
    }

    #[test]
    fn scaffold_typhon_toml_hints_optimise_level_and_still_parses() {
        let tmp = tempfile::tempdir().unwrap();
        run(InitArgs {
            name: Some("opt".into()),
            dir: tmp.path().to_path_buf(),
        })
        .unwrap();
        let toml = std::fs::read_to_string(tmp.path().join("opt/typhon.toml")).unwrap();
        // The hint is present, commented (so the default stays level 0), and
        // names the four knobs it flips.
        assert!(
            toml.contains("# [optimise]") && toml.contains("# level = 1"),
            "commented [optimise] hint missing from generated typhon.toml:\n{toml}"
        );
        assert!(
            toml.contains("auto-memoise") && toml.contains("pgo-memoise"),
            "optimise hint should name the flipped knobs:\n{toml}"
        );
        // The generated scaffold must remain valid, parseable config with the
        // hint commented out (level defaults to 0).
        let cfg: crate::config::TyphonConfig =
            toml::from_str(&toml).expect("generated typhon.toml must parse");
        assert_eq!(cfg.optimise.level, 0);
    }

    #[test]
    fn a_name_that_cannot_round_trip_through_toml_is_rejected() {
        // `tyc init 'a"b'` wrote `name = "a"b"` — a manifest the very next
        // command could not parse.
        for bad in ["a\"b", "", "-lead", "trail-", "a b", "a\nb", "café"] {
            assert!(
                validate_project_name(bad).is_err(),
                "`{bad}` must be rejected"
            );
        }
        for good in ["a", "my-app", "my_app", "a.b", "proj2"] {
            assert_eq!(validate_project_name(good).unwrap(), good);
        }
    }

    #[test]
    fn an_inferred_name_is_sanitised_rather_than_rejected() {
        // A directory called `my project` is perfectly ordinary, so
        // `tyc init` with no NAME coerces instead of refusing.
        assert_eq!(sanitise_project_name("my project"), "my-project");
        assert_eq!(sanitise_project_name("a\"b"), "a-b");
        assert_eq!(sanitise_project_name("--weird--"), "weird");
        assert_eq!(sanitise_project_name(""), "myproject");
        assert_eq!(sanitise_project_name("!!!"), "myproject");
        assert_eq!(
            sanitise_project_name("Already-Fine_1.0"),
            "Already-Fine_1.0"
        );
        for raw in ["my project", "a\"b", "--weird--", "", "!!!", "café"] {
            let out = sanitise_project_name(raw);
            assert!(
                project_name_is_valid(&out),
                "sanitising {raw:?} produced an invalid name {out:?}"
            );
        }
    }

    /// W4-14: the scaffold must not pin the optimiser knobs to `false` — an
    /// explicit `[strictness]` entry beats `[optimise] level` and `-O`, so the
    /// pinned scaffold made `tyc build -O` a no-op on every new project.
    #[test]
    fn scaffold_leaves_the_optimiser_knobs_to_the_optimise_level() {
        let toml = render_typhon_toml("opt");
        for knob in [
            "auto-memoise",
            "auto-gather",
            "auto-parallel",
            "pgo-memoise",
        ] {
            assert!(
                !toml.lines().any(|l| l.trim_start().starts_with(knob)),
                "{knob} must not be set in the scaffold:\n{toml}"
            );
        }
        let mut cfg: crate::config::TyphonConfig = toml::from_str(&toml).unwrap();
        cfg.resolve_optimise(true);
        assert_eq!(cfg.strictness.auto_memoise, Some(true));
        assert_eq!(cfg.strictness.auto_gather, Some(true));
        assert_eq!(cfg.strictness.pgo_memoise, Some(true));
        assert_eq!(cfg.strictness.auto_parallel, Some(true));
        let mut cfg: crate::config::TyphonConfig = toml::from_str(&toml).unwrap();
        cfg.resolve_optimise(false);
        assert_eq!(cfg.strictness.auto_memoise, Some(false));
    }

    /// W4-14: `tyc init` into a directory that already has `src/main.ty`
    /// fails before writing anything (it used to leave a `typhon.toml` and
    /// `tests/` behind, so the re-run then failed on the `typhon.toml`).
    #[test]
    fn init_over_an_existing_main_ty_writes_nothing() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(tmp.path().join("src")).unwrap();
        std::fs::write(tmp.path().join("src/main.ty"), "print(1)\n").unwrap();
        let err = run(InitArgs {
            name: None,
            dir: tmp.path().to_path_buf(),
        })
        .unwrap_err();
        assert!(err.to_string().contains("src/main.ty"), "{err}");
        assert!(!tmp.path().join("typhon.toml").exists());
        assert!(!tmp.path().join("tests").exists());
        assert_eq!(
            std::fs::read_to_string(tmp.path().join("src/main.ty")).unwrap(),
            "print(1)\n"
        );
    }

    /// `tyc init` never writes through a planted symlink.
    #[cfg(unix)]
    #[test]
    fn init_refuses_a_symlinked_manifest_path() {
        let tmp = tempfile::tempdir().unwrap();
        let victim = tmp.path().join("victim.txt");
        let proj = tmp.path().join("proj");
        std::fs::create_dir_all(&proj).unwrap();
        // A dangling link: `exists()` is false, so only a symlink-aware write
        // notices it.
        std::os::unix::fs::symlink(&victim, proj.join("typhon.toml")).unwrap();
        assert!(run(InitArgs {
            name: None,
            dir: proj.clone(),
        })
        .is_err());
        assert!(!victim.exists(), "wrote through the symlink");
    }
}
