//! `tyc init` — scaffold a new Typhon project.

use std::path::PathBuf;

use clap::Args;
use miette::{miette, Result};

use crate::config::{
    EmitConfig, EnvConfig, ProjectConfig, PythonConfig, StrictnessConfig, TyphonConfig,
};

/// Arguments for `tyc init`.
#[derive(Args, Debug)]
pub struct InitArgs {
    /// Name of the new project (defaults to the directory name).
    #[arg(value_name = "NAME")]
    pub name: Option<String>,

    /// Directory to initialise (defaults to current directory).
    #[arg(long, short = 'd', value_name = "DIR", default_value = ".")]
    pub dir: PathBuf,
}

pub fn run(args: InitArgs) -> Result<()> {
    // When a `NAME` is supplied, scaffold into `<dir>/<NAME>/` — matching the
    // convention of `cargo new`, `bun init NAME`, `uv init NAME`. When only
    // `--dir` is supplied (no name), scaffold into that directory and infer
    // the project name from its basename.
    let (dir, name) = match args.name {
        Some(name) => {
            let target = args.dir.join(&name);
            std::fs::create_dir_all(&target)
                .map_err(|e| miette!("cannot create {}: {}", target.display(), e))?;
            let canonical = target.canonicalize().unwrap_or(target);
            (canonical, name)
        }
        None => {
            let base = args.dir.canonicalize().unwrap_or(args.dir.clone());
            let inferred = base
                .file_name()
                .and_then(|n| n.to_str())
                .unwrap_or("myproject")
                .to_owned();
            (base, inferred)
        }
    };

    // Refuse to overwrite an existing typhon.toml.
    let config_path = dir.join("typhon.toml");
    if config_path.exists() {
        return Err(miette!("typhon.toml already exists in {}", dir.display()));
    }

    // Create directory structure.
    let src_dir = dir.join("src");
    let tests_dir = dir.join("tests");
    std::fs::create_dir_all(&src_dir).map_err(|e| miette!("cannot create src/: {}", e))?;
    std::fs::create_dir_all(&tests_dir).map_err(|e| miette!("cannot create tests/: {}", e))?;

    // Write typhon.toml.
    let config = TyphonConfig {
        project: ProjectConfig {
            name: name.clone(),
            version: "0.1.0".into(),
            src: "src".into(),
            out: "build".into(),
        },
        python: PythonConfig::default(),
        emit: EmitConfig::default(),
        strictness: StrictnessConfig::default(),
        env: EnvConfig::default(),
        dependencies: Default::default(),
        dev_dependencies: Default::default(),
    };
    let toml_str = config
        .to_toml_string()
        .map_err(|e| miette!("cannot serialise typhon.toml: {}", e))?;
    std::fs::write(&config_path, toml_str)
        .map_err(|e| miette!("cannot write typhon.toml: {}", e))?;

    // Write a starter main.ty — refuse to overwrite if it already exists.
    let main_ty_path = src_dir.join("main.ty");
    if main_ty_path.exists() {
        return Err(miette!(
            "src/main.ty already exists in {}; remove it first to re-scaffold",
            dir.display()
        ));
    }
    let main_ty = format!(
        r#"# {name} — entry point
#
# generated by `tyc init`

let greeting: str = "Hello from Typhon!"

def main() -> None:
    print(greeting)


if __name__ == "__main__":
    main()
"#,
        name = name
    );
    std::fs::write(&main_ty_path, main_ty)
        .map_err(|e| miette!("cannot write src/main.ty: {}", e))?;

    println!("Initialised Typhon project `{}` in {}", name, dir.display());
    println!("  typhon.toml");
    println!("  src/main.ty");
    println!("  tests/");

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn init_creates_project_structure() {
        let tmp = tempfile::tempdir().unwrap();
        let args = InitArgs {
            name: Some("myapp".into()),
            dir: tmp.path().to_path_buf(),
        };
        run(args).unwrap();
        let project = tmp.path().join("myapp");
        assert!(project.join("typhon.toml").exists(), "typhon.toml missing");
        assert!(project.join("src").is_dir(), "src/ dir missing");
        assert!(project.join("src/main.ty").exists(), "src/main.ty missing");
        assert!(project.join("tests").is_dir(), "tests/ dir missing");
    }

    #[test]
    fn init_with_name_creates_subdirectory() {
        // `tyc init NAME` should scaffold into `./NAME/`, not the CWD,
        // matching `cargo new` / `bun init NAME` / `uv init NAME` semantics.
        let tmp = tempfile::tempdir().unwrap();
        let args = InitArgs {
            name: Some("hello".into()),
            dir: tmp.path().to_path_buf(),
        };
        run(args).unwrap();
        assert!(
            tmp.path().join("hello/typhon.toml").exists(),
            "typhon.toml should land in the named subdirectory"
        );
        assert!(
            !tmp.path().join("typhon.toml").exists(),
            "typhon.toml must not leak into the parent directory"
        );
    }

    #[test]
    fn init_writes_project_name_into_toml() {
        let tmp = tempfile::tempdir().unwrap();
        let args = InitArgs {
            name: Some("coolproject".into()),
            dir: tmp.path().to_path_buf(),
        };
        run(args).unwrap();
        let toml = std::fs::read_to_string(tmp.path().join("coolproject/typhon.toml")).unwrap();
        assert!(
            toml.contains("coolproject"),
            "project name not in typhon.toml"
        );
    }

    #[test]
    fn init_rejects_existing_toml() {
        let tmp = tempfile::tempdir().unwrap();
        // First init succeeds.
        run(InitArgs {
            name: Some("proj".into()),
            dir: tmp.path().to_path_buf(),
        })
        .unwrap();
        // Second init on the same dir + name must fail.
        let result = run(InitArgs {
            name: Some("proj".into()),
            dir: tmp.path().to_path_buf(),
        });
        assert!(
            result.is_err(),
            "expected error when typhon.toml already exists"
        );
    }

    #[test]
    fn init_writes_main_ty_with_let_not_deprecated_val() {
        let tmp = tempfile::tempdir().unwrap();
        let args = InitArgs {
            name: Some("regression".into()),
            dir: tmp.path().to_path_buf(),
        };
        run(args).unwrap();
        let body = std::fs::read_to_string(tmp.path().join("regression/src/main.ty")).unwrap();
        assert!(
            !body.split_whitespace().any(|tok| tok == "val"),
            "scaffold leaked the deprecated `val` keyword:\n{body}"
        );
        assert!(
            body.contains("let "),
            "scaffold should use the current `let` keyword:\n{body}"
        );
    }

    #[test]
    fn init_uses_dir_name_when_no_name_given() {
        let tmp = tempfile::tempdir().unwrap();
        let args = InitArgs {
            name: None,
            dir: tmp.path().to_path_buf(),
        };
        // Should succeed (infers name from temp dir name).
        run(args).unwrap();
        assert!(tmp.path().join("typhon.toml").exists());
    }
}
