//! `ttc init` — scaffold a new Typhon project.

use std::path::PathBuf;

use clap::Args;
use miette::{miette, Result};

use crate::config::{
    EmitConfig, EnvConfig, ProjectConfig, PythonConfig, StrictnessConfig, TyphonConfig,
};

/// Arguments for `ttc init`.
#[derive(Args, Debug)]
pub struct InitArgs {
    /// Name of the new project (defaults to the directory name).
    #[arg(value_name = "NAME")]
    pub name: Option<String>,

    /// Directory to initialise (defaults to current directory).
    #[arg(long, short = 'd', value_name = "DIR", default_value = ".")]
    pub dir: PathBuf,
}

pub fn run(args: InitArgs) -> Result<()> {
    let dir = args.dir.canonicalize().unwrap_or(args.dir.clone());

    let name = args.name.unwrap_or_else(|| {
        dir.file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("myproject")
            .to_owned()
    });

    // Refuse to overwrite an existing typhon.toml.
    let config_path = dir.join("typhon.toml");
    if config_path.exists() {
        return Err(miette!(
            "typhon.toml already exists in {}",
            dir.display()
        ));
    }

    // Create directory structure.
    let src_dir = dir.join("src");
    let tests_dir = dir.join("tests");
    std::fs::create_dir_all(&src_dir)
        .map_err(|e| miette!("cannot create src/: {}", e))?;
    std::fs::create_dir_all(&tests_dir)
        .map_err(|e| miette!("cannot create tests/: {}", e))?;

    // Write typhon.toml.
    let config = TyphonConfig {
        project: ProjectConfig {
            name: name.clone(),
            version: "0.1.0".into(),
            src: "src".into(),
            out: "build".into(),
        },
        python: PythonConfig::default(),
        emit: EmitConfig::default(),
        strictness: StrictnessConfig::default(),
        env: EnvConfig::default(),
    };
    std::fs::write(&config_path, config.to_toml_string())
        .map_err(|e| miette!("cannot write typhon.toml: {}", e))?;

    // Write a starter main.tt.
    let main_tt = format!(
        r#"# {name} — entry point
#
# generated by `ttc init`

val greeting: str = "Hello from Typhon!"

def main() -> None:
    print(greeting)
"#,
        name = name
    );
    std::fs::write(src_dir.join("main.tt"), main_tt)
        .map_err(|e| miette!("cannot write src/main.tt: {}", e))?;

    println!("Initialised Typhon project `{}` in {}", name, dir.display());
    println!("  typhon.toml");
    println!("  src/main.tt");
    println!("  tests/");

    Ok(())
}
